spring.application.name=Ecomerce-Backend

spring.datasource.url=jdbc:postgresql://ep-broad-wave-aycddnmx-pooler.c-5.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_lU9dnTkPA8wG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

file.upload-dir=C:/Users/DELL/Desktop/Ecomerce-Backend/Ecomerce-Backend/uploads/profile
server.port=8080